### ISSUE TITLE
Question: How to invert zoom-in/zoom-out?

### ISSUE THREAD

**Issue by AlighaThor** [Divirad/PinchPanCamera#8]
First try in Godot 4.2.2, works wonders.
Quick question: Any way to invert the zoom-in/zoom-out (pinch)? For some reason, I have an opposite effect here (it's inverted).

Amazing addon!

**Comment by thismusicdude** [comment]
Thank you so so much! and thank you for your comment!

sorry for the late reply! i will look into it! :)

**Comment by thismusicdude** [comment]
@AlighaThor i'll add n option where you can invert the mouse wheel zoom. I'll have to take a closer look at the touchscreen zooming

**Comment by thismusicdude** [comment]
I added two separate new options for your request and took the chance to refactor a bit and add some quality of life changes lol

![image](https://github.com/user-attachments/assets/95931a20-148f-4e6a-84e3-2f3c43a2ab73)

Unfortunately, I don't have an android setup running at the moment, so it might take a while until i get a release version ready
but i'm going to publish my current feature branch and you can ofc download and use it :) feel free to tell me if it works~

**Comment by thismusicdude** [comment]
The feature is on [feature/invert_zoom](https://github.com/Divirad/PinchPanCamera/tree/feature/invert_zoom) branch
feel free to test it out :)

**Comment by thismusicdude** [comment]
[v1.0](https://github.com/Divirad/PinchPanCamera/releases/tag/v1.0) implemented and works with android! :) 
hope that helps
